// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.3
// source: queries.proto

package relayproto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type QueryParamsIsAncestor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DigestLE            []byte `protobuf:"bytes,1,opt,name=digest_l_e,json=digestLE,proto3" json:"digest_l_e,omitempty"`
	ProspectiveAncestor []byte `protobuf:"bytes,2,opt,name=prospective_ancestor,json=prospectiveAncestor,proto3" json:"prospective_ancestor,omitempty"`
	Limit               uint32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *QueryParamsIsAncestor) Reset() {
	*x = QueryParamsIsAncestor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queries_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryParamsIsAncestor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsIsAncestor) ProtoMessage() {}

func (x *QueryParamsIsAncestor) ProtoReflect() protoreflect.Message {
	mi := &file_queries_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsIsAncestor.ProtoReflect.Descriptor instead.
func (*QueryParamsIsAncestor) Descriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{0}
}

func (x *QueryParamsIsAncestor) GetDigestLE() []byte {
	if x != nil {
		return x.DigestLE
	}
	return nil
}

func (x *QueryParamsIsAncestor) GetProspectiveAncestor() []byte {
	if x != nil {
		return x.ProspectiveAncestor
	}
	return nil
}

func (x *QueryParamsIsAncestor) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type QueryResIsAncestor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Params *QueryParamsIsAncestor `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	Res    bool                   `protobuf:"varint,2,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *QueryResIsAncestor) Reset() {
	*x = QueryResIsAncestor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queries_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryResIsAncestor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResIsAncestor) ProtoMessage() {}

func (x *QueryResIsAncestor) ProtoReflect() protoreflect.Message {
	mi := &file_queries_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResIsAncestor.ProtoReflect.Descriptor instead.
func (*QueryResIsAncestor) Descriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{1}
}

func (x *QueryResIsAncestor) GetParams() *QueryParamsIsAncestor {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *QueryResIsAncestor) GetRes() bool {
	if x != nil {
		return x.Res
	}
	return false
}

type QueryResGetRelayGenesis struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res []byte `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *QueryResGetRelayGenesis) Reset() {
	*x = QueryResGetRelayGenesis{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queries_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryResGetRelayGenesis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResGetRelayGenesis) ProtoMessage() {}

func (x *QueryResGetRelayGenesis) ProtoReflect() protoreflect.Message {
	mi := &file_queries_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResGetRelayGenesis.ProtoReflect.Descriptor instead.
func (*QueryResGetRelayGenesis) Descriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{2}
}

func (x *QueryResGetRelayGenesis) GetRes() []byte {
	if x != nil {
		return x.Res
	}
	return nil
}

type QueryResGetLastReorgLCA struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res []byte `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *QueryResGetLastReorgLCA) Reset() {
	*x = QueryResGetLastReorgLCA{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queries_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryResGetLastReorgLCA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResGetLastReorgLCA) ProtoMessage() {}

func (x *QueryResGetLastReorgLCA) ProtoReflect() protoreflect.Message {
	mi := &file_queries_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResGetLastReorgLCA.ProtoReflect.Descriptor instead.
func (*QueryResGetLastReorgLCA) Descriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{3}
}

func (x *QueryResGetLastReorgLCA) GetRes() []byte {
	if x != nil {
		return x.Res
	}
	return nil
}

type QueryResGetBestDigest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res []byte `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *QueryResGetBestDigest) Reset() {
	*x = QueryResGetBestDigest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queries_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryResGetBestDigest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResGetBestDigest) ProtoMessage() {}

func (x *QueryResGetBestDigest) ProtoReflect() protoreflect.Message {
	mi := &file_queries_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResGetBestDigest.ProtoReflect.Descriptor instead.
func (*QueryResGetBestDigest) Descriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{4}
}

func (x *QueryResGetBestDigest) GetRes() []byte {
	if x != nil {
		return x.Res
	}
	return nil
}

type QueryParamsFindAncestor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DigestLE []byte `protobuf:"bytes,1,opt,name=digest_l_e,json=digestLE,proto3" json:"digest_l_e,omitempty"`
	Offset   uint32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *QueryParamsFindAncestor) Reset() {
	*x = QueryParamsFindAncestor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queries_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryParamsFindAncestor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsFindAncestor) ProtoMessage() {}

func (x *QueryParamsFindAncestor) ProtoReflect() protoreflect.Message {
	mi := &file_queries_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsFindAncestor.ProtoReflect.Descriptor instead.
func (*QueryParamsFindAncestor) Descriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{5}
}

func (x *QueryParamsFindAncestor) GetDigestLE() []byte {
	if x != nil {
		return x.DigestLE
	}
	return nil
}

func (x *QueryParamsFindAncestor) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type QueryResFindAncestor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Params *QueryParamsFindAncestor `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	Res    []byte                   `protobuf:"bytes,2,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *QueryResFindAncestor) Reset() {
	*x = QueryResFindAncestor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queries_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryResFindAncestor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResFindAncestor) ProtoMessage() {}

func (x *QueryResFindAncestor) ProtoReflect() protoreflect.Message {
	mi := &file_queries_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResFindAncestor.ProtoReflect.Descriptor instead.
func (*QueryResFindAncestor) Descriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{6}
}

func (x *QueryResFindAncestor) GetParams() *QueryParamsFindAncestor {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *QueryResFindAncestor) GetRes() []byte {
	if x != nil {
		return x.Res
	}
	return nil
}

type QueryParamsHeaviestFromAncestor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ancestor    []byte `protobuf:"bytes,1,opt,name=ancestor,proto3" json:"ancestor,omitempty"`
	CurrentBest []byte `protobuf:"bytes,2,opt,name=current_best,json=currentBest,proto3" json:"current_best,omitempty"`
	NewBest     []byte `protobuf:"bytes,3,opt,name=new_best,json=newBest,proto3" json:"new_best,omitempty"`
	Limit       uint32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *QueryParamsHeaviestFromAncestor) Reset() {
	*x = QueryParamsHeaviestFromAncestor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queries_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryParamsHeaviestFromAncestor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsHeaviestFromAncestor) ProtoMessage() {}

func (x *QueryParamsHeaviestFromAncestor) ProtoReflect() protoreflect.Message {
	mi := &file_queries_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsHeaviestFromAncestor.ProtoReflect.Descriptor instead.
func (*QueryParamsHeaviestFromAncestor) Descriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{7}
}

func (x *QueryParamsHeaviestFromAncestor) GetAncestor() []byte {
	if x != nil {
		return x.Ancestor
	}
	return nil
}

func (x *QueryParamsHeaviestFromAncestor) GetCurrentBest() []byte {
	if x != nil {
		return x.CurrentBest
	}
	return nil
}

func (x *QueryParamsHeaviestFromAncestor) GetNewBest() []byte {
	if x != nil {
		return x.NewBest
	}
	return nil
}

func (x *QueryParamsHeaviestFromAncestor) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type QueryResHeaviestFromAncestor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Params *QueryParamsHeaviestFromAncestor `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	Res    []byte                           `protobuf:"bytes,2,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *QueryResHeaviestFromAncestor) Reset() {
	*x = QueryResHeaviestFromAncestor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queries_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryResHeaviestFromAncestor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResHeaviestFromAncestor) ProtoMessage() {}

func (x *QueryResHeaviestFromAncestor) ProtoReflect() protoreflect.Message {
	mi := &file_queries_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResHeaviestFromAncestor.ProtoReflect.Descriptor instead.
func (*QueryResHeaviestFromAncestor) Descriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{8}
}

func (x *QueryResHeaviestFromAncestor) GetParams() *QueryParamsHeaviestFromAncestor {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *QueryResHeaviestFromAncestor) GetRes() []byte {
	if x != nil {
		return x.Res
	}
	return nil
}

type QueryParamsIsMostRecentCommonAncestor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ancestor []byte `protobuf:"bytes,1,opt,name=ancestor,proto3" json:"ancestor,omitempty"`
	Left     []byte `protobuf:"bytes,2,opt,name=left,proto3" json:"left,omitempty"`
	Right    []byte `protobuf:"bytes,3,opt,name=right,proto3" json:"right,omitempty"`
	Limit    uint32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *QueryParamsIsMostRecentCommonAncestor) Reset() {
	*x = QueryParamsIsMostRecentCommonAncestor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queries_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryParamsIsMostRecentCommonAncestor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsIsMostRecentCommonAncestor) ProtoMessage() {}

func (x *QueryParamsIsMostRecentCommonAncestor) ProtoReflect() protoreflect.Message {
	mi := &file_queries_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsIsMostRecentCommonAncestor.ProtoReflect.Descriptor instead.
func (*QueryParamsIsMostRecentCommonAncestor) Descriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{9}
}

func (x *QueryParamsIsMostRecentCommonAncestor) GetAncestor() []byte {
	if x != nil {
		return x.Ancestor
	}
	return nil
}

func (x *QueryParamsIsMostRecentCommonAncestor) GetLeft() []byte {
	if x != nil {
		return x.Left
	}
	return nil
}

func (x *QueryParamsIsMostRecentCommonAncestor) GetRight() []byte {
	if x != nil {
		return x.Right
	}
	return nil
}

func (x *QueryParamsIsMostRecentCommonAncestor) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type QueryResIsMostRecentCommonAncestor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Params *QueryParamsIsMostRecentCommonAncestor `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	Res    bool                                   `protobuf:"varint,2,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *QueryResIsMostRecentCommonAncestor) Reset() {
	*x = QueryResIsMostRecentCommonAncestor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queries_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryResIsMostRecentCommonAncestor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResIsMostRecentCommonAncestor) ProtoMessage() {}

func (x *QueryResIsMostRecentCommonAncestor) ProtoReflect() protoreflect.Message {
	mi := &file_queries_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResIsMostRecentCommonAncestor.ProtoReflect.Descriptor instead.
func (*QueryResIsMostRecentCommonAncestor) Descriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{10}
}

func (x *QueryResIsMostRecentCommonAncestor) GetParams() *QueryParamsIsMostRecentCommonAncestor {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *QueryResIsMostRecentCommonAncestor) GetRes() bool {
	if x != nil {
		return x.Res
	}
	return false
}

type QueryParamsGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID []byte `protobuf:"bytes,1,opt,name=i_d,json=iD,proto3" json:"i_d,omitempty"`
}

func (x *QueryParamsGetRequest) Reset() {
	*x = QueryParamsGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queries_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryParamsGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsGetRequest) ProtoMessage() {}

func (x *QueryParamsGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_queries_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsGetRequest.ProtoReflect.Descriptor instead.
func (*QueryParamsGetRequest) Descriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{11}
}

func (x *QueryParamsGetRequest) GetID() []byte {
	if x != nil {
		return x.ID
	}
	return nil
}

type QueryResGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Params *QueryParamsGetRequest `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	Res    *ProofRequest          `protobuf:"bytes,2,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *QueryResGetRequest) Reset() {
	*x = QueryResGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queries_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryResGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResGetRequest) ProtoMessage() {}

func (x *QueryResGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_queries_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResGetRequest.ProtoReflect.Descriptor instead.
func (*QueryResGetRequest) Descriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{12}
}

func (x *QueryResGetRequest) GetParams() *QueryParamsGetRequest {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *QueryResGetRequest) GetRes() *ProofRequest {
	if x != nil {
		return x.Res
	}
	return nil
}

type QueryParamsCheckRequests struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filled *FilledRequests `protobuf:"bytes,1,opt,name=filled,proto3" json:"filled,omitempty"`
}

func (x *QueryParamsCheckRequests) Reset() {
	*x = QueryParamsCheckRequests{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queries_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryParamsCheckRequests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsCheckRequests) ProtoMessage() {}

func (x *QueryParamsCheckRequests) ProtoReflect() protoreflect.Message {
	mi := &file_queries_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsCheckRequests.ProtoReflect.Descriptor instead.
func (*QueryParamsCheckRequests) Descriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{13}
}

func (x *QueryParamsCheckRequests) GetFilled() *FilledRequests {
	if x != nil {
		return x.Filled
	}
	return nil
}

type QueryResCheckRequests struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Params *QueryParamsCheckRequests `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	Valid  bool                      `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	Error  *string                   `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
}

func (x *QueryResCheckRequests) Reset() {
	*x = QueryResCheckRequests{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queries_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryResCheckRequests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResCheckRequests) ProtoMessage() {}

func (x *QueryResCheckRequests) ProtoReflect() protoreflect.Message {
	mi := &file_queries_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResCheckRequests.ProtoReflect.Descriptor instead.
func (*QueryResCheckRequests) Descriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{14}
}

func (x *QueryResCheckRequests) GetParams() *QueryParamsCheckRequests {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *QueryResCheckRequests) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *QueryResCheckRequests) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type QueryParamsCheckProof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Proof *SPVProof `protobuf:"bytes,1,opt,name=proof,proto3" json:"proof,omitempty"`
}

func (x *QueryParamsCheckProof) Reset() {
	*x = QueryParamsCheckProof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queries_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryParamsCheckProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsCheckProof) ProtoMessage() {}

func (x *QueryParamsCheckProof) ProtoReflect() protoreflect.Message {
	mi := &file_queries_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsCheckProof.ProtoReflect.Descriptor instead.
func (*QueryParamsCheckProof) Descriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{15}
}

func (x *QueryParamsCheckProof) GetProof() *SPVProof {
	if x != nil {
		return x.Proof
	}
	return nil
}

type QueryResCheckProof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Params *QueryParamsCheckProof `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	Valid  bool                   `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	Error  *string                `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
}

func (x *QueryResCheckProof) Reset() {
	*x = QueryResCheckProof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queries_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryResCheckProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResCheckProof) ProtoMessage() {}

func (x *QueryResCheckProof) ProtoReflect() protoreflect.Message {
	mi := &file_queries_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResCheckProof.ProtoReflect.Descriptor instead.
func (*QueryResCheckProof) Descriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{16}
}

func (x *QueryResCheckProof) GetParams() *QueryParamsCheckProof {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *QueryResCheckProof) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *QueryResCheckProof) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_queries_proto protoreflect.FileDescriptor

var file_queries_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0a, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x73, 0x68, 0x61,
	0x72, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7e, 0x0a, 0x15, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x49, 0x73, 0x41, 0x6e, 0x63, 0x65, 0x73, 0x74,
	0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x0a, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x5f, 0x6c, 0x5f, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x4c, 0x45,
	0x12, 0x31, 0x0a, 0x14, 0x70, 0x72, 0x6f, 0x73, 0x70, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f,
	0x61, 0x6e, 0x63, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x13,
	0x70, 0x72, 0x6f, 0x73, 0x70, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x41, 0x6e, 0x63, 0x65, 0x73,
	0x74, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x61, 0x0a, 0x12, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x52, 0x65, 0x73, 0x49, 0x73, 0x41, 0x6e, 0x63, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x12,
	0x39, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x21, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x49, 0x73, 0x41, 0x6e, 0x63, 0x65, 0x73, 0x74,
	0x6f, 0x72, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x72, 0x65, 0x73, 0x22, 0x2b, 0x0a, 0x17,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x6c, 0x61, 0x79,
	0x47, 0x65, 0x6e, 0x65, 0x73, 0x69, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x72, 0x65, 0x73, 0x22, 0x2b, 0x0a, 0x17, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x52, 0x65, 0x73, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x52, 0x65, 0x6f, 0x72,
	0x67, 0x4c, 0x43, 0x41, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x03, 0x72, 0x65, 0x73, 0x22, 0x29, 0x0a, 0x15, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52,
	0x65, 0x73, 0x47, 0x65, 0x74, 0x42, 0x65, 0x73, 0x74, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x72, 0x65,
	0x73, 0x22, 0x4f, 0x0a, 0x17, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x46, 0x69, 0x6e, 0x64, 0x41, 0x6e, 0x63, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x0a,
	0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x5f, 0x6c, 0x5f, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x08, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x4c, 0x45, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x22, 0x65, 0x0a, 0x14, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x46, 0x69,
	0x6e, 0x64, 0x41, 0x6e, 0x63, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x12, 0x3b, 0x0a, 0x06, 0x70, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x72, 0x65, 0x6c,
	0x61, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6e, 0x63, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x52,
	0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x72, 0x65, 0x73, 0x22, 0x91, 0x01, 0x0a, 0x1f, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x48, 0x65, 0x61, 0x76, 0x69, 0x65, 0x73,
	0x74, 0x46, 0x72, 0x6f, 0x6d, 0x41, 0x6e, 0x63, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x12, 0x1a, 0x0a,
	0x08, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x08, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x5f, 0x62, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x42, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08,
	0x6e, 0x65, 0x77, 0x5f, 0x62, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07,
	0x6e, 0x65, 0x77, 0x42, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x75, 0x0a,
	0x1c, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x48, 0x65, 0x61, 0x76, 0x69, 0x65, 0x73,
	0x74, 0x46, 0x72, 0x6f, 0x6d, 0x41, 0x6e, 0x63, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x12, 0x43, 0x0a,
	0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e,
	0x72, 0x65, 0x6c, 0x61, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x48, 0x65, 0x61, 0x76, 0x69, 0x65, 0x73, 0x74, 0x46, 0x72,
	0x6f, 0x6d, 0x41, 0x6e, 0x63, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x03, 0x72, 0x65, 0x73, 0x22, 0x83, 0x01, 0x0a, 0x25, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x49, 0x73, 0x4d, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74,
	0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x41, 0x6e, 0x63, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x12, 0x1a,
	0x0a, 0x08, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x08, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x65,
	0x66, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x72, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x72,
	0x69, 0x67, 0x68, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x81, 0x01, 0x0a, 0x22, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x49, 0x73, 0x4d, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x63,
	0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x41, 0x6e, 0x63, 0x65, 0x73, 0x74, 0x6f,
	0x72, 0x12, 0x49, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x31, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x49, 0x73, 0x4d, 0x6f, 0x73, 0x74,
	0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x41, 0x6e, 0x63, 0x65,
	0x73, 0x74, 0x6f, 0x72, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x72, 0x65, 0x73, 0x22, 0x28,
	0x0a, 0x15, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0f, 0x0a, 0x03, 0x69, 0x5f, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x44, 0x22, 0x7b, 0x0a, 0x12, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x52, 0x65, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39,
	0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21,
	0x2e, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x2a, 0x0a, 0x03, 0x72, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x52, 0x03, 0x72, 0x65, 0x73, 0x22, 0x4e, 0x0a, 0x18, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x73, 0x12, 0x32, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46,
	0x69, 0x6c, 0x6c, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x52, 0x06, 0x66,
	0x69, 0x6c, 0x6c, 0x65, 0x64, 0x22, 0x90, 0x01, 0x0a, 0x15, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52,
	0x65, 0x73, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x12,
	0x3c, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x24, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x73, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x42, 0x08,
	0x0a, 0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x43, 0x0a, 0x15, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x6f,
	0x66, 0x12, 0x2a, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x50,
	0x56, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x22, 0x8a, 0x01,
	0x0a, 0x12, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50,
	0x72, 0x6f, 0x6f, 0x66, 0x12, 0x39, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x88, 0x01, 0x01,
	0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x2d, 0x74,
	0x78, 0x2f, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x73, 0x2f, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_queries_proto_rawDescOnce sync.Once
	file_queries_proto_rawDescData = file_queries_proto_rawDesc
)

func file_queries_proto_rawDescGZIP() []byte {
	file_queries_proto_rawDescOnce.Do(func() {
		file_queries_proto_rawDescData = protoimpl.X.CompressGZIP(file_queries_proto_rawDescData)
	})
	return file_queries_proto_rawDescData
}

var file_queries_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_queries_proto_goTypes = []interface{}{
	(*QueryParamsIsAncestor)(nil),                 // 0: relayproto.QueryParamsIsAncestor
	(*QueryResIsAncestor)(nil),                    // 1: relayproto.QueryResIsAncestor
	(*QueryResGetRelayGenesis)(nil),               // 2: relayproto.QueryResGetRelayGenesis
	(*QueryResGetLastReorgLCA)(nil),               // 3: relayproto.QueryResGetLastReorgLCA
	(*QueryResGetBestDigest)(nil),                 // 4: relayproto.QueryResGetBestDigest
	(*QueryParamsFindAncestor)(nil),               // 5: relayproto.QueryParamsFindAncestor
	(*QueryResFindAncestor)(nil),                  // 6: relayproto.QueryResFindAncestor
	(*QueryParamsHeaviestFromAncestor)(nil),       // 7: relayproto.QueryParamsHeaviestFromAncestor
	(*QueryResHeaviestFromAncestor)(nil),          // 8: relayproto.QueryResHeaviestFromAncestor
	(*QueryParamsIsMostRecentCommonAncestor)(nil), // 9: relayproto.QueryParamsIsMostRecentCommonAncestor
	(*QueryResIsMostRecentCommonAncestor)(nil),    // 10: relayproto.QueryResIsMostRecentCommonAncestor
	(*QueryParamsGetRequest)(nil),                 // 11: relayproto.QueryParamsGetRequest
	(*QueryResGetRequest)(nil),                    // 12: relayproto.QueryResGetRequest
	(*QueryParamsCheckRequests)(nil),              // 13: relayproto.QueryParamsCheckRequests
	(*QueryResCheckRequests)(nil),                 // 14: relayproto.QueryResCheckRequests
	(*QueryParamsCheckProof)(nil),                 // 15: relayproto.QueryParamsCheckProof
	(*QueryResCheckProof)(nil),                    // 16: relayproto.QueryResCheckProof
	(*ProofRequest)(nil),                          // 17: relayproto.ProofRequest
	(*FilledRequests)(nil),                        // 18: relayproto.FilledRequests
	(*SPVProof)(nil),                              // 19: relayproto.SPVProof
}
var file_queries_proto_depIdxs = []int32{
	0,  // 0: relayproto.QueryResIsAncestor.params:type_name -> relayproto.QueryParamsIsAncestor
	5,  // 1: relayproto.QueryResFindAncestor.params:type_name -> relayproto.QueryParamsFindAncestor
	7,  // 2: relayproto.QueryResHeaviestFromAncestor.params:type_name -> relayproto.QueryParamsHeaviestFromAncestor
	9,  // 3: relayproto.QueryResIsMostRecentCommonAncestor.params:type_name -> relayproto.QueryParamsIsMostRecentCommonAncestor
	11, // 4: relayproto.QueryResGetRequest.params:type_name -> relayproto.QueryParamsGetRequest
	17, // 5: relayproto.QueryResGetRequest.res:type_name -> relayproto.ProofRequest
	18, // 6: relayproto.QueryParamsCheckRequests.filled:type_name -> relayproto.FilledRequests
	13, // 7: relayproto.QueryResCheckRequests.params:type_name -> relayproto.QueryParamsCheckRequests
	19, // 8: relayproto.QueryParamsCheckProof.proof:type_name -> relayproto.SPVProof
	15, // 9: relayproto.QueryResCheckProof.params:type_name -> relayproto.QueryParamsCheckProof
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_queries_proto_init() }
func file_queries_proto_init() {
	if File_queries_proto != nil {
		return
	}
	file_shared_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_queries_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryParamsIsAncestor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queries_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryResIsAncestor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queries_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryResGetRelayGenesis); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queries_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryResGetLastReorgLCA); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queries_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryResGetBestDigest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queries_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryParamsFindAncestor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queries_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryResFindAncestor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queries_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryParamsHeaviestFromAncestor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queries_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryResHeaviestFromAncestor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queries_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryParamsIsMostRecentCommonAncestor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queries_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryResIsMostRecentCommonAncestor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queries_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryParamsGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queries_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryResGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queries_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryParamsCheckRequests); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queries_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryResCheckRequests); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queries_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryParamsCheckProof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queries_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryResCheckProof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_queries_proto_msgTypes[14].OneofWrappers = []interface{}{}
	file_queries_proto_msgTypes[16].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_queries_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_queries_proto_goTypes,
		DependencyIndexes: file_queries_proto_depIdxs,
		MessageInfos:      file_queries_proto_msgTypes,
	}.Build()
	File_queries_proto = out.File
	file_queries_proto_rawDesc = nil
	file_queries_proto_goTypes = nil
	file_queries_proto_depIdxs = nil
}
